version: '3'
services:
  pritunl-zero:
    depends_on:
      - mongodb
    image: 'pritunl/pritunl-zero'
    container_name: 'pritunl-zero'
    environment:
      - MONGO_URI=${MONGO_URI}
      - NODE_ID=${NODE_ID}
    ports:
      - '80:80'
      - '443:443'
  mongodb:
    image: 'mongo'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE}
      - MONGO_USER=${USERNAME}
      - MONGO_PASS=${PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  website:
    image: 'ponsfrilus/2048nginx'
    container_name: 'website'

volumes:
  mongo-data: